apiVersion: v1
data:
  pg_hba.conf: |
    host all all all trust
    --dbname \"$POSTGRES_DB\" <<-EOSQL\n\tCREATE USER dev;\n\tCREATE DATABASE dev;\n\tGRANT
    ALL PRIVILEGES ON DATABASE docker TO docker;\nEOSQL\n"
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: configmap-postgres-etc
