apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: svc-frontend
  name: svc-frontend
spec:
  ports:
  - name: 8000-8000
    nodePort: 30001
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: frontend
  type: NodePort
status:
  loadBalancer: {}
